// examples/react/src/App.tsx
import React, { ChangeEvent, Dispatch, useEffect, useRef, useState } from 'react';
import {
  EmbeddedBootstrapConfig,
  EmbeddedBootstrapConfigBase,
  ISwapFormEmbeddedController,
  Locale
} from '@one-inch-community/models';
import { bootstrapEmbedded } from '@one-inch-community/integration-layer/embedded';
import './App.css';

function App() {

  const [swapController, setSwapController] = useState<ISwapFormEmbeddedController | null>(null);
  const [configView, setConfigView] = useState<string>();
  const [themeType, setThemeType] = useState<EmbeddedBootstrapConfigBase['themeType']>('dark');
  const [locale, setLocale] = useState<EmbeddedBootstrapConfigBase['locale']>(Locale.en);
  const [primaryColor, setPrimaryColor] = useState<EmbeddedBootstrapConfigBase['primaryColor']>('#73b500');
  const [chainId, setChainId] = useState<EmbeddedBootstrapConfigBase['chainId']>(137);
  const [sourceTokenSymbol, setSourceTokenSymbol] = useState<string>('usdc');
  const [destinationTokenSymbol, setDestinationTokenSymbol] = useState<string>('usdt');
  const [amount, setAmount] = useState<string>('');
  const [disabledTokenChanging, setDisabledTokenChanging] = useState<boolean>(true);

  const disabledTokenChangingRef = useRef<boolean>(disabledTokenChanging);
  const themeTypeRef = useRef<EmbeddedBootstrapConfigBase['themeType']>(themeType);

  const getConfig = (): EmbeddedBootstrapConfig => ({
    themeType,
    locale,
    primaryColor,
    chainId,
    oneInchDevPortal: 'https://jellyfish-app-8xwqz.ondigitalocean.app',
    renderContainer: '#container',
    widgetName: 'swap-from',
    walletProvider: window.ethereum,
    swapFromParams: {
      sourceTokenSymbol,
      destinationTokenSymbol,
      disabledTokenChanging
    }
  });

  const destroy = () => {
    swapController?.destroy();
    setSwapController(null);
  };

  const bootstrap = () => {
    let isCancel = false;
    const handler = async () => {
      if (swapController && !swapController.isDestroyed) return;
      const config = getConfig();
      const controller = await bootstrapEmbedded(config);
      if (isCancel) {
        controller.destroy();
        return;
      }
      setSwapController(controller);
      updateConfigView();
    };
    handler().then();
    return () => {
      isCancel = true;
    };
  };

  const updateConfigView = () => {
    const config: any = getConfig();
    config.walletProvider = 'window.ethereum';
    const configView = JSON.stringify(config, null, 2);
    setConfigView(configView);
  };

  const changeHandler = (setter: Dispatch<any>) => (event: ChangeEvent<HTMLInputElement | HTMLSelectElement>) => {
    setter(event.target.value);
  }

  useEffect(() => {
    return bootstrap();
  }, []);

  useEffect(() => {
    if (disabledTokenChangingRef.current === disabledTokenChanging) return
    destroy()
    const handler = bootstrap()
    disabledTokenChangingRef.current = disabledTokenChanging
    updateConfigView()
    return handler
  }, [disabledTokenChanging])

  useEffect(() => {
    if (themeType === themeTypeRef.current) return
    swapController?.setThemeType(themeType).then()
    themeTypeRef.current = themeType
    updateConfigView()
  }, [ themeType ])

  return (
    <div className="main">
      <div>
        <div id="container"></div>
        <textarea
          value={configView}
          className="config-view"
          readOnly={true}
        >
      </textarea>
      </div>

      <div className="controls">
        <button onClick={() => destroy()}>Destroy</button>
        <button onClick={() => bootstrap()}>Bootstrap</button>

        <label className="input">
          <span>source token symbol</span>
          <input value={sourceTokenSymbol} onChange={changeHandler(setSourceTokenSymbol)}
                 placeholder="source token symbol" />
        </label>
        <button onClick={async () => {
          await swapController?.setToken('source', sourceTokenSymbol)
          updateConfigView()
        }}>Set
        </button>

        <label className="input">
          <span>destination token symbol</span>
          <input value={destinationTokenSymbol} onChange={changeHandler(setDestinationTokenSymbol)}
                 placeholder="destination token symbol" />
        </label>
        <button onClick={async () => {
          await swapController?.setToken('destination', destinationTokenSymbol)
          updateConfigView()
        }}>Set
        </button>

        <label className="input">
          <span>amount</span>
          <input value={amount} onChange={changeHandler(setAmount)}
                 placeholder="amount" />
        </label>
        <button onClick={async () => {
          await swapController?.setSourceTokenAmount(amount)
          updateConfigView()
        }}>Set
        </button>

        <label className="input">
          <span>chain id</span>
          <input value={chainId} onChange={changeHandler(setChainId)}
                 placeholder="chain id" />
        </label>
        <button onClick={async () => {
          await swapController?.setChainId(chainId)
          updateConfigView()
        }}>Set
        </button>

        <label className="input">
          <span>primary color</span>
          <input value={primaryColor} onChange={changeHandler(setPrimaryColor)}
                 placeholder="primary color" />
        </label>
        <button onClick={async () => {
          await swapController?.setThemePrimaryColor(primaryColor)
          updateConfigView()
        }}>Set
        </button>

        <label className="input">
          <span>locale</span>
          <select value={locale} onChange={changeHandler(setLocale)} name="locale">
            <option value={Locale.en}>{Locale.en}</option>
            <option value={Locale.fr}>{Locale.fr}</option>
            <option value={Locale.ar}>{Locale.ar}</option>
            <option value={Locale.de}>{Locale.de}</option>
            <option value={Locale.es}>{Locale.es}</option>
          </select>
        </label>
        <button onClick={async () => {
          await swapController?.setLocale(locale)
          updateConfigView()
        }}>Set
        </button>

        <label className="input">
          <span>disabled change token</span>
        </label>
        <input type="checkbox" checked={disabledTokenChanging} onChange={(event) => {
          setDisabledTokenChanging(event.target.checked);
        }} placeholder="disabled change token" />

        <span>theme</span>

        <div>
          <span>dark</span>
          <input type="radio" value="dark" checked={themeType === 'dark'} onChange={changeHandler(setThemeType)} />

          <span>light</span>
          <input type="radio" value="light" checked={themeType === 'light'} onChange={changeHandler(setThemeType)} />
        </div>

      </div>
    </div>
  )
    ;
}

export default App;

// examples/angular/one-inch-community-embedded-example/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { bootstrapEmbedded } from '@one-inch-community/integration-layer/embedded';
import { ColorHex, EmbeddedBootstrapConfig, ISwapFormEmbeddedController, Locale } from '@one-inch-community/models';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet, FormsModule],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css',
})
export class AppComponent implements OnInit {

  private swapFromController?: ISwapFormEmbeddedController

  protected Locale = Locale

  protected sourceTokenSymbol = 'usdt'
  protected destinationTokenSymbol = 'usdc'
  protected chainId = '137'
  protected primaryColor: ColorHex = '#73b500'
  protected locale: Locale = Locale.en
  protected _themeType: 'dark' | 'light' = 'dark'
  protected _disabledTokenChanging = true
  protected amount = ''

  protected exampleConfig: unknown

  get themeType() {
    return this._themeType
  }

  set themeType(state: 'dark' | 'light') {
    this._themeType = state
    this.swapFromController?.setThemeType(state).then()
    this.updateExampleConfig()
  }

  get disabledTokenChanging() {
    return this._disabledTokenChanging
  }

  set disabledTokenChanging(state: boolean) {
    this._disabledTokenChanging = state
    this.onDestroy()
    this.onBootstrap().then()
  }

  async ngOnInit() {
    await this.onBootstrap()
  }

  async onBootstrap() {
    if (this.swapFromController) return
    this.swapFromController = await bootstrapEmbedded(this.getConfig());
    this.updateExampleConfig()
  }

  onDestroy() {
    this.swapFromController?.destroy();
    this.swapFromController = undefined
  }

  protected async setSourceTokenSymbol() {
    await this.swapFromController?.setToken('source', this.sourceTokenSymbol)
    this.updateExampleConfig()
  }

  protected async setDestinationTokenSymbol() {
    await this.swapFromController?.setToken('destination', this.destinationTokenSymbol)
    this.updateExampleConfig()
  }

  protected async setChainId() {
    await this.swapFromController?.setChainId(Number(this.chainId))
    this.updateExampleConfig()
  }

  protected async setPrimaryColor() {
    await this.swapFromController?.setThemePrimaryColor(this.primaryColor)
  }

  protected async setAmount() {
    await this.swapFromController?.setSourceTokenAmount(this.amount)
  }

  protected async setLocale() {
    await this.swapFromController?.setLocale(this.locale)
    this.updateExampleConfig()
  }

  private updateExampleConfig() {
    const config: any = this.getConfig()
    config.walletProvider = 'window.ethereum'
    this.exampleConfig = JSON.stringify(config, null, 2)
  }

  private getConfig(): EmbeddedBootstrapConfig {
    return {
      renderContainer: '#container',
      widgetName: 'swap-from',
      oneInchDevPortal: 'https://jellyfish-app-8xwqz.ondigitalocean.app',
      themeType: this.themeType,
      locale: this.locale,
      primaryColor: this.primaryColor,
      walletProvider: window.ethereum,
      chainId: Number(this.chainId),
      swapFromParams: {
        disabledTokenChanging: this.disabledTokenChanging,
        sourceTokenSymbol: this.sourceTokenSymbol,
        destinationTokenSymbol: this.destinationTokenSymbol,
      }
    }
  }
}

<div>
  <div id="container"></div>

  <textarea
    class="config-view"
    readonly
    [ngModel]="exampleConfig"
  ></textarea>
</div>
<div class="controls">
  <button (click)="onBootstrap()">Bootstrap</button>
  <button (click)="onDestroy()">Destroy</button>

  <label class="input">
    <span>source token symbol</span>
    <input [(ngModel)]="sourceTokenSymbol" placeholder="source token symbol">
  </label>
  <button (click)="setSourceTokenSymbol()">Set</button>

  <label class="input">
    <span>destination token symbol</span>
    <input [(ngModel)]="destinationTokenSymbol" placeholder="destination token symbol">
  </label>
  <button (click)="setDestinationTokenSymbol()">Set</button>

  <label class="input">
    <span>amount</span>
    <input [(ngModel)]="amount" placeholder="amount">
  </label>
  <button (click)="setAmount()">Set</button>

  <label class="input">
    <span>chain id</span>
    <input [(ngModel)]="chainId" placeholder="chain id">
  </label>
  <button (click)="setChainId()">Set</button>

  <label class="input">
    <span>primary color</span>
    <input [(ngModel)]="primaryColor" placeholder="primary color">
  </label>
  <button (click)="setPrimaryColor()">Set</button>

  <label class="input">
    <span>locale</span>
    <select [(ngModel)]="locale" name="locale">
      <option value="{{Locale.en}}">{{Locale.en}}</option>
      <option value="{{Locale.fr}}">{{Locale.fr}}</option>
      <option value="{{Locale.ar}}">{{Locale.ar}}</option>
      <option value="{{Locale.de}}">{{Locale.de}}</option>
      <option value="{{Locale.es}}">{{Locale.es}}</option>
    </select>
  </label>
  <button (click)="setLocale()">Set</button>

  <label class="input">
    <span>disabled change token</span>
  </label>
  <input type="checkbox" [(ngModel)]="disabledTokenChanging" placeholder="disabled change token">

  <span>theme</span>

  <div>
    <span>dark</span>
    <input type="radio" value="dark" [(ngModel)]="themeType">

    <span>light</span>
    <input type="radio" value="light" [(ngModel)]="themeType">
  </div>

</div>
